### ISSUE TITLE
Usage of CC-BY-NC licensed code.

### ISSUE THREAD

**Issue by brother** [pkojchevski/budgetify#1]
Hi
Not sure what your intended audience is but the project references highcharts and that module is dual licensed restricted source the free (gratis) code is under CC-BY-NC while you can buy a usage license if needed in a commercial project. 

Maybe consider changing that module to something else to make it easier to use the project in a commercial setting. Just a thought.

See also:
https://github.com/highcharts/highcharts/issues/4405#issuecomment-125124004
https://shop.highsoft.com/faq#Non-Commercial-0

**Comment by pkojchevski** [comment]
Actually in app I was using nvd3. That module I forgot to delete it.
Thank You for the tip. I deleted the module.
